/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.client.views.dialogs;

import com.client.update.UpdateClientService;
import com.retrait.add.AddRetraitService;
import com.versement.add.AddVersementService;
import org.json.JSONObject;

/**
 *
 * @author rcara
 */
public class MultifunctionDialog extends javax.swing.JDialog {

    /**
     * Creates new form AddTransactionDialog
     */
    public final UpdateClientService updateClientService;
    public final AddVersementService addVersementService;
    public final AddRetraitService addRetraitService;
    
    public MultifunctionDialog(java.awt.Frame parent) {
        super(parent, true);
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("/com/images/banking.png")));
        setLocationRelativeTo(null);
        initComponents();

        updateClientService = new UpdateClientService();
        addVersementService = new AddVersementService();
        addRetraitService = new AddRetraitService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        clientSituationsOperationPanel1 = new javax.swing.JPanel();
        clientSituationsOperationField = new javax.swing.JTextField();
        clientSituationSubmitOperationButton = new javax.swing.JButton();
        clientSituationCancelOperationButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        setSize(new java.awt.Dimension(386, 220));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        clientSituationsOperationPanel1.setBackground(new java.awt.Color(35, 47, 64));
        clientSituationsOperationPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Entrer la valeur", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(204, 204, 255))); // NOI18N

        clientSituationsOperationField.setBackground(new java.awt.Color(58, 67, 80));
        clientSituationsOperationField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        clientSituationsOperationField.setForeground(new java.awt.Color(204, 204, 204));
        clientSituationsOperationField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        clientSituationsOperationField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        clientSituationsOperationField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                clientSituationsOperationFieldKeyReleased(evt);
            }
        });

        clientSituationSubmitOperationButton.setForeground(new java.awt.Color(204, 204, 204));
        clientSituationSubmitOperationButton.setText("Valider");
        clientSituationSubmitOperationButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        clientSituationSubmitOperationButton.setContentAreaFilled(false);
        clientSituationSubmitOperationButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clientSituationSubmitOperationButton.setFocusPainted(false);
        clientSituationSubmitOperationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientSituationSubmitOperationButtonMouseClicked(evt);
            }
        });

        clientSituationCancelOperationButton.setForeground(new java.awt.Color(204, 204, 204));
        clientSituationCancelOperationButton.setText("Annuler");
        clientSituationCancelOperationButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        clientSituationCancelOperationButton.setContentAreaFilled(false);
        clientSituationCancelOperationButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clientSituationCancelOperationButton.setFocusPainted(false);
        clientSituationCancelOperationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientSituationCancelOperationButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout clientSituationsOperationPanel1Layout = new javax.swing.GroupLayout(clientSituationsOperationPanel1);
        clientSituationsOperationPanel1.setLayout(clientSituationsOperationPanel1Layout);
        clientSituationsOperationPanel1Layout.setHorizontalGroup(
            clientSituationsOperationPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientSituationsOperationPanel1Layout.createSequentialGroup()
                .addGroup(clientSituationsOperationPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clientSituationsOperationPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(clientSituationSubmitOperationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(clientSituationCancelOperationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(clientSituationsOperationPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(clientSituationsOperationField, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        clientSituationsOperationPanel1Layout.setVerticalGroup(
            clientSituationsOperationPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientSituationsOperationPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(clientSituationsOperationField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(clientSituationsOperationPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clientSituationSubmitOperationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clientSituationCancelOperationButton, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clientSituationsOperationPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clientSituationsOperationPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientSituationsOperationFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clientSituationsOperationFieldKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == 10)
            submitClientSituationOperation();
    }//GEN-LAST:event_clientSituationsOperationFieldKeyReleased

    private void clientSituationSubmitOperationButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientSituationSubmitOperationButtonMouseClicked
        submitClientSituationOperation();
    }//GEN-LAST:event_clientSituationSubmitOperationButtonMouseClicked

    private void clientSituationCancelOperationButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientSituationCancelOperationButtonMouseClicked
        // TODO add your handling code here
        dispose();
    }//GEN-LAST:event_clientSituationCancelOperationButtonMouseClicked

    public void open(String title, JSONObject client) {
        switch(title.toUpperCase()) {
            case "VERSEMENT":
                setTitle("VERSEMENT [" + client.getString("id") + "]");
                clientSituationsOperationField.setText("0");
                addVersementService.setInput("id", client.getString("id"));
                break;
            case "RETRAIT":
                setTitle("RETRAIT [" + client.getString("id") + "]");
                clientSituationsOperationField.setText("0");
                addRetraitService.setInput("id", client.getString("id"));
                break;
            case "SOLDE": 
                setTitle("SOLDE [" + client.getString("id") + "]");
                String solde = String.valueOf(client.getInt("solde"));
                clientSituationsOperationField.setText(solde);
                
                updateClientService.set("id", client.getString("id"));
                updateClientService.set("nom", client.getString("nom"));
                updateClientService.set("solde", solde);
                break;
            case "NOM":
                setTitle("NOM [" + client.getString("id") + "]");
                clientSituationsOperationField.setText(client.getString("nom"));
                
                updateClientService.set("id", client.getString("id"));
                updateClientService.set("nom", client.getString("nom"));
                updateClientService.set("solde", String.valueOf(client.getInt("solde")));
                break;
        }
        setVisible(true);
    }
        /**Choose specific operation according to dialog title*/
    private void submitClientSituationOperation() {
        
        String operation = getTitle().substring(0, getTitle().indexOf(" ["));
        String data = clientSituationsOperationField.getText();
        
        switch(operation) {
            case "VERSEMENT":
                addVersementService.setInput(operation.toLowerCase(), data);
                addVersementService.submitAddVersment();
                break;
            case "RETRAIT":
                addRetraitService.setInput(operation.toLowerCase(), data);
                addRetraitService.submitAddRetrait();
                break;
            case "TRANSFERT":
                break;
            default: 
                updateClientService.set(operation.toLowerCase(), data);
                updateClientService.submitUpdateClient();
                break;
        }
        dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clientSituationCancelOperationButton;
    private javax.swing.JButton clientSituationSubmitOperationButton;
    private javax.swing.JTextField clientSituationsOperationField;
    private javax.swing.JPanel clientSituationsOperationPanel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
