/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.client.views.dialogs;

import com.client.read.ClientReader;
import com.transfer.add.FindReceiverService;
import com.transfer.add.AddTransfertService;
import com.transfer.cancel.CancelTransfertService;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author USER
 */
public class TransferDialog extends javax.swing.JDialog {

    /**
     * Creates new form TransferDialog
     */
    private JSONArray clients;
    private final FindReceiverService findReceiverClientService;
    private final AddTransfertService addTransfertService;
    private final CancelTransfertService cancelTransfertService;
    private boolean interchanged;
    private boolean hasTransfer;
    
    public TransferDialog() {
        
        super(new java.awt.Frame(), true);
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                clients.remove(1);//remove sender
                cancelButton.setEnabled(false);
                /**clear sender info*/
                clearReceiverInfos();
            }
        });
        setDefaultTitle();
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("/com/images/money_transfer.png")));
        
        clients = new JSONArray();
        
        initComponents();
        
        findReceiverClientService = new FindReceiverService();
        addTransfertService = new AddTransfertService();
        cancelTransfertService = new CancelTransfertService();
        /**Disable transfer button until have receiver and monttant>0*/
        setControlsEnabled();
        /**Disable cancel button till have done at list once transfer*/
        interchanged = false;
        hasTransfer = false;
        cancelButton.setEnabled(interchanged);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        receiverNameLabel = new javax.swing.JLabel();
        senderNumberLabel = new javax.swing.JLabel();
        senderSoldLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        receiverSearchField = new javax.swing.JTextField();
        senderNameLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        receiverSoldLabel = new javax.swing.JLabel();
        receiverNumberLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        montant = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        InterchangeRoleLabel = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(50, 69, 78));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Transfert d'argent", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(75, 92, 101));

        receiverNameLabel.setForeground(new java.awt.Color(204, 204, 204));
        receiverNameLabel.setText("Nom :");

        senderNumberLabel.setForeground(new java.awt.Color(204, 204, 204));
        senderNumberLabel.setText("N°Compte");

        senderSoldLabel.setForeground(new java.awt.Color(204, 204, 204));
        senderSoldLabel.setText("Solde");

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Montant de transfert :");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        receiverSearchField.setBackground(new java.awt.Color(75, 92, 101));
        receiverSearchField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        receiverSearchField.setForeground(new java.awt.Color(255, 255, 255));
        receiverSearchField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        receiverSearchField.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Recheche de recépteur", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        receiverSearchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                receiverSearchFieldKeyReleased(evt);
            }
        });

        senderNameLabel.setForeground(new java.awt.Color(204, 204, 204));
        senderNameLabel.setText("Nom");

        receiverSoldLabel.setForeground(new java.awt.Color(204, 204, 204));
        receiverSoldLabel.setText("Solde :");

        receiverNumberLabel.setForeground(new java.awt.Color(204, 204, 204));
        receiverNumberLabel.setText("N°Compte :");

        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Source d'envoi");

        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("BENEFICIAIRE");

        montant.setBackground(new java.awt.Color(75, 92, 101));
        montant.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        montant.setForeground(new java.awt.Color(204, 204, 204));
        montant.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        montant.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "valeur", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        montant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                montantKeyReleased(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(75, 92, 101));
        cancelButton.setForeground(new java.awt.Color(255, 255, 51));
        cancelButton.setText("Annuler le dernier transfert");
        cancelButton.setBorder(null);
        cancelButton.setContentAreaFilled(false);
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton.setFocusPainted(false);
        cancelButton.setOpaque(true);
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });

        okButton.setBackground(new java.awt.Color(75, 92, 101));
        okButton.setForeground(new java.awt.Color(204, 204, 255));
        okButton.setText("Effectuer l'opération");
        okButton.setBorder(null);
        okButton.setContentAreaFilled(false);
        okButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        okButton.setFocusPainted(false);
        okButton.setOpaque(true);
        okButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okButtonMouseClicked(evt);
            }
        });

        InterchangeRoleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InterchangeRoleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/invert_role.png"))); // NOI18N
        InterchangeRoleLabel.setToolTipText("Basculer le rôle");
        InterchangeRoleLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InterchangeRoleLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InterchangeRoleLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(montant, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(senderSoldLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(senderNumberLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(receiverNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(receiverNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(receiverSoldLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(receiverSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(InterchangeRoleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(senderNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(386, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(99, 99, 99)
                    .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(454, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(receiverSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(receiverNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(receiverNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(receiverSoldLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(senderNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(senderSoldLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(montant, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InterchangeRoleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(senderNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(248, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(293, Short.MAX_VALUE)
                    .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(21, 21, 21)))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setSender(JSONObject client) {
        clients.put(0, client);
        
        senderNameLabel.setText("Nom : " + client.getString("nom"));
        senderNumberLabel.setText("N°Compte : " + client.getString("id"));
        senderSoldLabel.setText("Solde : " + client.get("solde") + " Ariary");
    }
    private void setReceiver(JSONObject client) {
        clients.put(1, client);
        
        receiverNameLabel.setText("Nom : " + client.getString("nom"));
        receiverNumberLabel.setText("N°Compte : " + client.getString("id"));
        receiverSoldLabel.setText("Solde : " + client.get("solde") + " Ariary");
    }
    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        /**transfers are orderd by creattion date, so the last transfers is the sender's first transfer*/
        cancelTransfertService.setTransfert(clients.getJSONObject(0).getJSONArray("transferts").getJSONObject(0).getString("id"));
        
        JSONArray partners = cancelTransfertService.submitCancelTransfert();
        if(partners.length() > 0) {
            updateClient(partners);
            setDefaultTitle();
            hasTransfer = false;
        }
        ((javax.swing.JButton)evt.getSource()).setEnabled(hasTransfer);
    }//GEN-LAST:event_cancelButtonMouseClicked

    private void okButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButtonMouseClicked
        // set the inputs
        addTransfertService.setSender(clients.getJSONObject(0).getString("id"));
        addTransfertService.setReceiver(clients.getJSONObject(1).getString("id"));
        //Send
        JSONArray partners = addTransfertService.submitAddTransfert();
        if(partners.length() == 2) {
            updateClient(partners);
           
            String title = addTransfertService.getSender()+ " vers ";
            title += addTransfertService.getReceiver() + " [ Ar ";
            title += clients.getJSONObject(0).getJSONArray("transferts").getJSONObject(0).get("montant_transfert");
            setTitle("Transfert annulable : "  + title + " ]");
            
            interchanged = true;
            hasTransfer = true;
            /**Make transfer cancelling possible*/
            cancelButton.setEnabled(true);
        }
        
    }//GEN-LAST:event_okButtonMouseClicked

    private void receiverSearchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_receiverSearchFieldKeyReleased
        // TODO add your handling code here:
        switch(evt.getKeyCode()) {
            case 10:
                //The parteners have to be different each other
                findReceiverClientService.setSender(clients.getJSONObject(0).getString("id"));
                JSONObject client = findReceiverClientService.submitFindOneClient();
                
                if(client != null)setReceiver(client);
                else clearReceiverInfos();
                
                break;
            default: 
                findReceiverClientService.setKeyword(receiverSearchField.getText());
                break;
        }
        setControlsEnabled();
    }//GEN-LAST:event_receiverSearchFieldKeyReleased

    private void montantKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_montantKeyReleased
        // TODO add your handling code here:
        addTransfertService.setMontant(montant.getText());
        setControlsEnabled();
    }//GEN-LAST:event_montantKeyReleased

    private void InterchangeRoleLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InterchangeRoleLabelMouseClicked
        // TODO add your handling code here:
        if(InterchangeRoleLabel.isEnabled()) {
            JSONObject sender = clients.getJSONObject(0);
            setSender(clients.getJSONObject(1));
            setReceiver(sender);
            interchanged = !interchanged;
            /**If clients sender position wan't changed,and transfer exists**/
            cancelButton.setEnabled(interchanged && hasTransfer);
        }        
    }//GEN-LAST:event_InterchangeRoleLabelMouseClicked
    private void setControlsEnabled() {
        boolean active = clients.length() == 2;
        okButton.setEnabled(isPositiveNumber(montant.getText())&& active);
        InterchangeRoleLabel.setEnabled(active);
    }
    private boolean isPositiveNumber(String str) {
        return str == null ? false : str.matches("\\d*[1-9]{1,}0*$");
    }
    private void updateClient(JSONArray partners) {
        
        setSender(partners.getJSONObject(0));
        setReceiver(partners.getJSONObject(1));
        ClientReader.getInstance().updateClientList(clients.getJSONObject(0));
        ClientReader.getInstance().updateClientList(clients.getJSONObject(1));      
    }
    private void setDefaultTitle() {
        setTitle("Transfert annulable : aucun");
    }
    private void clearReceiverInfos() {
        receiverNameLabel.setText("Nom : ");
        receiverNumberLabel.setText("N°Compte : ");
        receiverSoldLabel.setText("Solde : ");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InterchangeRoleLabel;
    public javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField montant;
    public javax.swing.JButton okButton;
    private javax.swing.JLabel receiverNameLabel;
    private javax.swing.JLabel receiverNumberLabel;
    private javax.swing.JTextField receiverSearchField;
    private javax.swing.JLabel receiverSoldLabel;
    private javax.swing.JLabel senderNameLabel;
    private javax.swing.JLabel senderNumberLabel;
    private javax.swing.JLabel senderSoldLabel;
    // End of variables declaration//GEN-END:variables
}
