/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.client.views;

import com.client.read.ClientReader;
import com.client.views.table.ButtonEditor;
import com.client.views.table.LabelRenderer;
import com.client.views.table.TableModel;
import com.client.views.table.TextFieldEditor;
import javax.swing.plaf.basic.BasicScrollBarUI;
import javax.swing.table.DefaultTableCellRenderer;
import org.json.JSONArray;
/**
 *
 * @author USER
 */
public class BankMovement extends javax.swing.JPanel {

    public TableModel tableModel;
    /**
     * Creates new form MoreAboutCLient
     */
    public BankMovement() {
        
        initComponents();
        tableModel = new TableModel();
        clientBankMovementTable.setModel(tableModel);
        clientBankMovementTable.getTableHeader().setBackground(new java.awt.Color(101,123,134));
        clientBankMovementTable.getTableHeader().setForeground(new java.awt.Color(204,204,255));
        clientBankMovementTable.setForeground(new java.awt.Color(204,204,255));
        
        tableModel.addObserver(new shared.observing.Observer() {
            @Override
            public void update() {
                 setAboutClient();
            }
        });
        
        //TextFieldTableListener
        TextFieldEditor fieldEditor = new TextFieldEditor();
        clientBankMovementTable.getColumn("VERSEMENT").setCellEditor(fieldEditor);
        clientBankMovementTable.getColumn("RETRAIT").setCellEditor(fieldEditor);

        clientBankMovementTable.getColumn("SUPPRESSION").setCellRenderer(new LabelRenderer());
        /**Delete and restore solde*/
        clientBankMovementTable.getColumn("SUPPRESSION").setCellEditor(new ButtonEditor());
        
        DefaultTableCellRenderer defaultCellRenderer = new DefaultTableCellRenderer();
        defaultCellRenderer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        defaultCellRenderer.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
        int columnCount = clientBankMovementTable.getModel().getColumnCount() - 1;
        for(int i = 0; i < columnCount; i++)
            clientBankMovementTable.getColumn(clientBankMovementTable.getModel().getColumnName(i)).setCellRenderer(defaultCellRenderer);
        this.clientFluxScrollPanel.getVerticalScrollBar().setUI(new BasicScrollBarUI() {
            @Override
            protected void configureScrollBarColors() {
                this.thumbColor = new java.awt.Color(111, 121, 133);
                this.trackColor = new java.awt.Color(75, 92, 101);
                this.scrollBarWidth = 15;
            }
        });
        yearField.setText(ClientReader.getInstance().getYear());
        transactionButton.setText("Voir les transactions " + yearField.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        clientBankMovementPanel = new javax.swing.JPanel();
        clientFluxScrollPanel = new javax.swing.JScrollPane();
        clientBankMovementTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        yearField = new javax.swing.JFormattedTextField();
        transactionButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setLayout(new java.awt.GridLayout(1, 1, 0, 10));

        clientBankMovementPanel.setBackground(new java.awt.Color(43, 78, 95));
        clientBankMovementPanel.setPreferredSize(new java.awt.Dimension(472, 180));
        clientBankMovementPanel.setLayout(new java.awt.BorderLayout(0, 20));

        clientFluxScrollPanel.setBackground(new java.awt.Color(54, 78, 90));

        clientBankMovementTable.setBackground(new java.awt.Color(54, 78, 90));
        clientBankMovementTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        clientBankMovementTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        clientBankMovementTable.setForeground(new java.awt.Color(255, 255, 255));
        clientBankMovementTable.setFillsViewportHeight(true);
        clientBankMovementTable.setGridColor(new java.awt.Color(204, 204, 204));
        clientBankMovementTable.setRowHeight(30);
        clientBankMovementTable.setSelectionBackground(new java.awt.Color(0, 153, 153));
        clientBankMovementTable.setSelectionForeground(new java.awt.Color(204, 204, 204));
        clientBankMovementTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        clientFluxScrollPanel.setViewportView(clientBankMovementTable);

        clientBankMovementPanel.add(clientFluxScrollPanel, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(54, 78, 90));
        jPanel1.setPreferredSize(new java.awt.Dimension(415, 200));
        jPanel1.setLayout(new java.awt.GridLayout(2, 1, 10, 10));

        jPanel2.setBackground(new java.awt.Color(43, 78, 95));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Transactions bancaires annuelles", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel2.setLayout(new java.awt.GridLayout(1, 3, 30, 0));

        yearField.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Année de référence", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        yearField.setForeground(new java.awt.Color(204, 204, 204));
        try {
            yearField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        yearField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        yearField.setText("0");
        yearField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        yearField.setOpaque(false);
        yearField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                yearFieldKeyReleased(evt);
            }
        });
        jPanel2.add(yearField);

        transactionButton.setBackground(new java.awt.Color(101, 123, 134));
        transactionButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        transactionButton.setForeground(new java.awt.Color(0, 153, 153));
        transactionButton.setText("valider");
        transactionButton.setBorder(null);
        transactionButton.setContentAreaFilled(false);
        transactionButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transactionButton.setFocusPainted(false);
        transactionButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        transactionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionButtonActionPerformed(evt);
            }
        });
        jPanel2.add(transactionButton);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/banck_transaction.png"))); // NOI18N
        jPanel2.add(jLabel1);

        jPanel1.add(jPanel2);

        clientSuggestions.setBackground(new java.awt.Color(43, 78, 95));
        clientSuggestions.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(43, 78, 95), 1, true), "Informations du client", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        clientSuggestions.setPreferredSize(new java.awt.Dimension(562, 60));
        clientSuggestions.setLayout(new java.awt.GridLayout(3, 2, 0, 8));
        jPanel1.add(clientSuggestions);

        clientBankMovementPanel.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jSplitPane1.setRightComponent(clientBankMovementPanel);

        ClientSuggestionsPanel.setBackground(new java.awt.Color(35, 47, 64));
        ClientSuggestionsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clients suggérés", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(204, 204, 255)), "Suggestion de clients", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(204, 204, 255))); // NOI18N
        ClientSuggestionsPanel.setPreferredSize(new java.awt.Dimension(300, 330));
        ClientSuggestionsPanel.setLayout(new java.awt.GridLayout(0, 1, 0, 5));
        jSplitPane1.setLeftComponent(ClientSuggestionsPanel);

        add(jSplitPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void transactionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionButtonActionPerformed
        // TODO add your handling code here:
        ClientReader.getInstance().submitSearchClient();
    }//GEN-LAST:event_transactionButtonActionPerformed

    private void yearFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearFieldKeyReleased
        // TODO add your handling code here:
        switch(evt.getKeyCode()) {
            case 10 :
            ClientReader.getInstance().submitSearchClient();
            break;
            default:
            ClientReader.getInstance().setYear(yearField.getText());
            transactionButton.setText("Voir les transactions " + yearField.getText());
            break;
        }
    }//GEN-LAST:event_yearFieldKeyReleased

    private void setAboutClient() {
        if(tableModel.client != null) {
            /**To visualize when values changed*/
            int width = clientBankMovementTable.getColumn("SUPPRESSION").getWidth();
            clientBankMovementTable.getColumn("SUPPRESSION").setWidth(width - 1);
            clientBankMovementTable.getColumn("SUPPRESSION").setWidth(width + 1);

            clientSuggestions.removeAll();
            clientSuggestions.add(new CustomLabelView("N°Compte : " + tableModel.client.get("id")));
            clientSuggestions.add(new CustomLabelView("Nom : " + tableModel.client.get("nom")));
            clientSuggestions.add(new CustomLabelView("Date de création : " + tableModel.client.get("created_at")));
            clientSuggestions.add(new CustomLabelView("Dernière mise à jour : " + tableModel.client.get("updated_at")));
            
            int versement = ((JSONArray)tableModel.client.get("versements")).length();
            int retrait = ((JSONArray)tableModel.client.get("retraits")).length();
            clientSuggestions.add(new CustomLabelView("Versement : " + String.valueOf(versement) + " fois"));
            clientSuggestions.add(new CustomLabelView("Retrait : " + String.valueOf(retrait) + " fois"));
            
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public final javax.swing.JPanel ClientSuggestionsPanel = new javax.swing.JPanel();
    private javax.swing.JPanel clientBankMovementPanel;
    private javax.swing.JTable clientBankMovementTable;
    private javax.swing.JScrollPane clientFluxScrollPanel;
    private final javax.swing.JPanel clientSuggestions = new javax.swing.JPanel();
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton transactionButton;
    private javax.swing.JFormattedTextField yearField;
    // End of variables declaration//GEN-END:variables

}
