/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.client.views;

import com.client.read.ClientReader;
import javax.swing.plaf.basic.BasicScrollBarUI;
import org.json.JSONArray;
import shared.RequestConfig;
import shared.observing.Observer;
import shared.views.WrapLayout;

/**
 *
 * @author USER
 */
public class ClientHome extends javax.swing.JPanel {

    /**
     * Creates new form BankMovement
     */
    private final AddClientView addClientView;
    private final BankMovement bankMovement;
    
    public ClientHome() {
        
        initComponents();
        clientSituationsListPanel.setLayout(new WrapLayout());
        /**client situation observing*/
        ClientReader.getInstance().addObserver(new Observer() {
            @Override
            public void update() {
               updateClientListViews(); 
            }
        });
        /**AddCLientview*/
        this.addClientView = new AddClientView();

        this.HomeClientSplitPane.setTopComponent(this.addClientView);
        
        /***bankMovement*/
        bankMovement = new BankMovement();
        clientsFoundedTabbedPane.addTab("Mouvement bancaire d'un client", bankMovement);
        
        clientsFoundedTabbedPane.setTitleAt(0, "Situations des clients");
        clientsFoundedTabbedPane.setIconAt(0, new javax.swing.ImageIcon(getClass().getResource("/com/images/client_situations.png")));
        clientsFoundedTabbedPane.setIconAt(1, new javax.swing.ImageIcon(getClass().getResource("/com/images/wire-transfer.png")));
        clientSituationsListPanel.setLayout(new WrapLayout());
        clientsSituationsScrollPane.getVerticalScrollBar().setUI(new BasicScrollBarUI() {
            @Override
            protected void configureScrollBarColors() {
                this.thumbColor = new java.awt.Color(111, 121, 133);
                this.trackColor = new java.awt.Color(75, 92, 101);
                this.scrollBarWidth = 15;
            }
        });
        /**Listening requests**/
        shared.APIRequest.getInstance().addObserver(() -> {
            clientNotificationLabel.setText(RequestConfig.message);
        });
        /**Initializing of client situation*/
         ClientReader.getInstance().submitSearchClient();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HomeClientSplitPane = new javax.swing.JSplitPane();
        ClientHomeRightPartSplitPane = new javax.swing.JPanel();
        searchClientPanel = new javax.swing.JPanel();
        searchClientField = new javax.swing.JTextField();
        submitSearchClient = new javax.swing.JButton();
        clientNotificationPanel = new javax.swing.JPanel();
        clientNotificationLabel = new javax.swing.JLabel();
        clientsFoundedTabbedPane = new javax.swing.JTabbedPane();
        clientsSituationsScrollPane = new javax.swing.JScrollPane();
        clientSituationsListPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(31, 45, 64));
        setLayout(new java.awt.GridLayout(1, 0));

        HomeClientSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        ClientHomeRightPartSplitPane.setLayout(new java.awt.BorderLayout());

        searchClientPanel.setBackground(new java.awt.Color(50, 69, 78));
        searchClientPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 86, 107)), "Recherche d'un client quelconque", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(204, 204, 255))); // NOI18N
        searchClientPanel.setPreferredSize(new java.awt.Dimension(415, 82));

        searchClientField.setBackground(new java.awt.Color(75, 92, 101));
        searchClientField.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        searchClientField.setForeground(new java.awt.Color(255, 255, 255));
        searchClientField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        searchClientField.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "taper quelque chose", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        searchClientField.setPreferredSize(new java.awt.Dimension(300, 45));
        searchClientField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchClientFieldKeyReleased(evt);
            }
        });
        searchClientPanel.add(searchClientField);

        submitSearchClient.setBackground(new java.awt.Color(75, 92, 101));
        submitSearchClient.setForeground(new java.awt.Color(204, 204, 204));
        submitSearchClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/search.png"))); // NOI18N
        submitSearchClient.setText("chercher");
        submitSearchClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 99, 113)));
        submitSearchClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitSearchClient.setFocusPainted(false);
        submitSearchClient.setPreferredSize(new java.awt.Dimension(90, 45));
        submitSearchClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitSearchClientMouseClicked(evt);
            }
        });
        searchClientPanel.add(submitSearchClient);

        ClientHomeRightPartSplitPane.add(searchClientPanel, java.awt.BorderLayout.PAGE_START);

        clientNotificationPanel.setBackground(new java.awt.Color(43, 78, 95));
        clientNotificationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Barre De Notication", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 255))); // NOI18N
        clientNotificationPanel.setPreferredSize(new java.awt.Dimension(472, 50));
        clientNotificationPanel.setLayout(new java.awt.GridLayout(1, 1));

        clientNotificationLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clientNotificationLabel.setForeground(new java.awt.Color(255, 153, 0));
        clientNotificationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clientNotificationLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clientNotificationPanel.add(clientNotificationLabel);

        ClientHomeRightPartSplitPane.add(clientNotificationPanel, java.awt.BorderLayout.PAGE_END);

        clientsFoundedTabbedPane.setBackground(new java.awt.Color(35, 47, 64));
        clientsFoundedTabbedPane.setForeground(new java.awt.Color(255, 255, 255));
        clientsFoundedTabbedPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        clientsFoundedTabbedPane.setFocusable(false);
        clientsFoundedTabbedPane.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        clientsFoundedTabbedPane.setOpaque(true);
        clientsFoundedTabbedPane.setVerifyInputWhenFocusTarget(false);

        clientSituationsListPanel.setBackground(new java.awt.Color(31, 45, 64));
        clientSituationsListPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Clients Correspondants à la recherche", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(204, 204, 255))); // NOI18N
        clientSituationsListPanel.setLayout(null);
        clientsSituationsScrollPane.setViewportView(clientSituationsListPanel);

        clientsFoundedTabbedPane.addTab("tab2", clientsSituationsScrollPane);

        ClientHomeRightPartSplitPane.add(clientsFoundedTabbedPane, java.awt.BorderLayout.CENTER);

        HomeClientSplitPane.setBottomComponent(ClientHomeRightPartSplitPane);

        add(HomeClientSplitPane);
    }// </editor-fold>//GEN-END:initComponents

    private void submitSearchClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitSearchClientMouseClicked
        // TODO add your handling code here:
         ClientReader.getInstance().submitSearchClient();
    }//GEN-LAST:event_submitSearchClientMouseClicked

    private void searchClientFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchClientFieldKeyReleased

        switch(evt.getKeyCode()) {
            case 10: 
                 ClientReader.getInstance().submitSearchClient();
                break;
            default:
                 ClientReader.getInstance().setKeyword(this.searchClientField.getText());
                break;
        }
    }//GEN-LAST:event_searchClientFieldKeyReleased

    private void updateClientListViews() {
        
        JSONArray clients = ClientReader.getInstance().clientList();
        
        clientSituationsListPanel.removeAll();
        bankMovement.ClientSuggestionsPanel.removeAll();
        
        /**To update component views*/
        updateComponent();
        
        int count = clients.length();
        
        if(count > 0){
            
            bankMovement.tableModel.setData(clients.getJSONObject(0));

            for(int i = 0; i < count ; i++) {

                org.json.JSONObject client = clients.getJSONObject(i);

                clientSituationsListPanel.add(new ClientSituationsView(client));

                String nom = String.valueOf(i + 1) + " - " + client.getString("nom");

                CustomLabelView suggestionView = new CustomLabelView(nom);
                suggestionView.addMouseListener(new java.awt.event.MouseAdapter() {
                    @Override
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                       updateComponent();
                       bankMovement.tableModel.setData(client);
                    }
                });
                bankMovement.ClientSuggestionsPanel.add(suggestionView);
            }
        }
                      
    }
    private void updateComponent() {
        setEnabled(false);
        setEnabled(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ClientHomeRightPartSplitPane;
    private javax.swing.JSplitPane HomeClientSplitPane;
    private javax.swing.JLabel clientNotificationLabel;
    private javax.swing.JPanel clientNotificationPanel;
    private javax.swing.JPanel clientSituationsListPanel;
    private javax.swing.JTabbedPane clientsFoundedTabbedPane;
    private javax.swing.JScrollPane clientsSituationsScrollPane;
    private javax.swing.JTextField searchClientField;
    private javax.swing.JPanel searchClientPanel;
    private javax.swing.JButton submitSearchClient;
    // End of variables declaration//GEN-END:variables
}
